# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title for the campaign.', max_length=200)),
                ('slug', models.SlugField(help_text='The URL slug for this campaign.', max_length=200)),
                ('active', models.BooleanField(default=False, help_text='Is this campaign active?')),
                ('headline', models.CharField(help_text='Headline/call-to-action text for the page.', max_length=256)),
                ('subhead', models.TextField(help_text='Short sub-heading text for use in list pages and the meta description tag, in CommonMark format.')),
                ('body', models.TextField(help_text='Body text, in CommonMark format.')),
                ('suggested_amount', models.DecimalField(decimal_places=2, default=0, help_text='The suggested contribution amount -- the initial amount displayed to the user.', max_digits=10)),
                ('recipients', jsonfield.fields.JSONField(blank=True, default=[], help_text='A list of contribution recipients.')),
                ('total_contributors', models.IntegerField(default=0, help_text='A running total of the number of individuals who made a contribution through this Campaign.')),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, help_text='A running total of contributions made through this Campaign.', max_digits=10)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', jsonfield.fields.JSONField(help_text='Contributor name, address, occupation, and employer.')),
                ('amount', models.DecimalField(decimal_places=2, help_text="The contribution amount, in dollars --- the same amount the user's credit card was charged.", max_digits=6)),
                ('cclastfour', models.CharField(blank=True, db_index=True, help_text="The last four digits of the user's credit card number, stored & indexed for fast look-up in case we need to find a Contribution from a credit card number.", max_length=4, null=True)),
                ('recipients', jsonfield.fields.JSONField(help_text='A list of contribution recipients and the amount each recipient is receiving.')),
                ('transaction', jsonfield.fields.JSONField(help_text='The Democracy Engine transaction record.')),
                ('ref_code', models.CharField(blank=True, db_index=True, help_text='An optional referral code that lead the user to take this action, e.g. from a utm_campaign query string argument.', max_length=24, null=True)),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('campaign', models.ForeignKey(help_text='The Campaign that this Contribution was made for.', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='siteapp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Organization.', max_length=200)),
                ('slug', models.SlugField(help_text='The unique URL slug for this Organization.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descriptive text describing the Organization.')),
                ('extra', jsonfield.fields.JSONField(blank=True, help_text='Additional information stored with this object.')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(help_text='The organization which owns the Campaign.', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='siteapp.Organization'),
        ),
    ]
