# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="The contribution amount, in dollars --- the same amount the user's credit card was charged.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='transaction',
            field=jsonfield.fields.JSONField(blank=True, help_text='The Democracy Engine transaction record.'),
        ),
    ]
